apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./namespace.yaml
  - https://github.com:argoproj/argo-cd.git//manifests/core-install?ref=v2.2.3

images:
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: latest
