argo-cd:
  server:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      labels:
        sre.swimlane.io/labeled: "true"
      hosts: 
        - 'argocd.127.0.0.1.nip.io'
    extraArgs:
      - '--insecure'
    config:
      application.resourceTrackingMethod: annotation
      url: http://argocd.127.0.0.1.nip.io/
  controller:
    metrics:
      enabled: true
      service:
        annotations:
          prometheus.io/scrape: "true"
    args:
      appResyncPeriod: 20

argocd-image-updater:
  config:
  gitCommitUser: "argocd-kind"
  gitCommitMail: "argocd-kind"
  gitCommitTemplate: ""
  logLevel: "info"

argocd-notifications:
  argocdUrl: http://argocd.127.0.0.1.nip.io
  context:
    cluster: kind-lasrv-k8s
  secret:
    create: false
    name: "argocd-notifications-secret"
  cm:
    create: true
    name: "argocd-notifications-cm"
  # https://argocd-notifications.readthedocs.io/en/stable/subscriptions/
  subscriptions: 
    - recipients:
        - slack:larntz-kind-testing
      triggers:
        - on-deployed
        - on-health-degraded
        - on-sync-failed
        - on-sync-status-unknown

  # https://argocd-notifications.readthedocs.io/en/stable/catalog/#triggers
  triggers:
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        # this one is changed because it spams notifications for every app :: any commit
        # https://github.com/argoproj-labs/argocd-notifications/issues/173
        #oncePer: app.status.sync.revision
        oncePer: app.status.operationState.operation.sync.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
    trigger.on-out-of-sync: |
      - description: Application has degraded
        send:
        - app-sync-status-unknown
        when: app.status.sync.status == 'OutOfSync'
    trigger.on-health-degraded: |
      - description: Application has degraded
        send:
        - app-health-degraded
        when: app.status.health.status == 'Degraded'
    trigger.on-sync-failed: |
      - description: Application syncing has failed
        send:
        - app-sync-failed
        when: app.status.operationState.phase in ['Error', 'Failed']
    trigger.on-sync-running: |
      - description: Application is being synced
        send:
        - app-sync-running
        when: app.status.operationState.phase in ['Running']
    trigger.on-sync-status-unknown: |
      - description: Application status is 'Unknown'
        send:
        - app-sync-status-unknown
        when: app.status.sync.status == 'Unknown'
    trigger.on-sync-succeeded: |
      - description: Application syncing has succeeded
        send:
        - app-sync-succeeded
        when: app.status.operationState.phase in ['Succeeded']

  templates: 
    template.app-deployed: |
      slack:
        attachments: |
          [{
            "title": "app: {{ .app.metadata.name }} :: cluster: {{ .context.cluster }}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": false
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": false
            },
            {
              "title": "Revision",
              "value": "{{.app.status.sync.revision}}",
              "short": false
            },
            {
              "title": "Revision Author",
              "value": "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}",
              "short": false
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": false
            }
            {{end}}
            ]
          }]
    template.app-health-degraded: |
      slack:
        attachments: |-
          [{
            "title": "app: {{ .app.metadata.name }} :: cluster: {{ .context.cluster }}",
            "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#f4c030",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": false
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": false
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": false
            }
            {{end}}
            ]
          }]
    template.app-sync-failed: |
      slack:
        attachments: |-
          [{
            "title": "app: {{ .app.metadata.name }} :: cluster: {{ .context.cluster }}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#E96D76",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": false
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": false
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": false
            }
            {{end}}
            ]
          }]
    template.app-sync-running: |
      slack:
        attachments: |-
          [{
            "title": "app: {{ .app.metadata.name }} :: cluster: {{ .context.cluster }}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#0DADEA",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": false
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": false
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": false
            }
            {{end}}
            ]
          }]
    template.app-sync-status-unknown: |
      slack:
        attachments: |-
          [{
            "title": "app: {{ .app.metadata.name }} :: cluster: {{ .context.cluster }}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#E96D76",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": false
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": false
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": false
            }
            {{end}}
            ]
          }]
    template.app-sync-succeeded: |
      slack:
        attachments: |-
          [{
            "title": "app: {{ .app.metadata.name }} :: cluster: {{ .context.cluster }}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": false
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": false
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": false
            }
            {{end}}
            ]
          }]
